#include "EditorLocalization.h"
#include "EditorSettings.h"

#include <iterator>

namespace Editor
{
	namespace
	{
		using FaluEngine::Loc::Entry;

		const Entry kEntries[] = 
		{
			{ "AO Map", "AOマップ", nullptr },
			{ "Add Component", "コンポーネントを追加", nullptr },
			{ "Albedo Color", "アルベドカラー", nullptr },
			{ "Albedo Map", "アルベドマップ", nullptr },
			{ "Anchor Max", "アンカー最大", nullptr },
			{ "Anchor Min", "アンカー最小", nullptr },
			{ "Anchored Position", "アンカー位置", nullptr },
			{ "Animator Component", "アニメーターコンポーネント", nullptr },
			{ "Audio", "オーディオ", nullptr },
			{ "AudioSource Component", "オーディオソースコンポーネント", nullptr },
			{ "Bias", "バイアス", nullptr },
			{ "Body Type", "ボディタイプ", nullptr },
			{ "Bottom", "下", nullptr },
			{ "Brush Mode", "ブラシモード", nullptr },
			{ "Brush Radius", "ブラシ半径", nullptr },
			{ "Brush Strength", "ブラシ強度", nullptr },
			{ "Button Component", "ボタンコンポーネント", nullptr },
			{ "Camera Component", "カメラコンポーネント", nullptr },
			{ "Cancel", "キャンセル", nullptr },
			{ "Canvas Component", "キャンバスコンポーネント", nullptr },
			{ "Cast Shadow", "影を落とす", nullptr },
			{ "Category (Tag)", "カテゴリ(タグ)", nullptr },
			{ "Claude API Key", "Claude APIキー", nullptr },
			{ "Clip Path", "クリップパス", nullptr },
			{ "Color", "色", nullptr },
			{ "Computed Position: (%.1f, %.1f)", "計算後の位置: (%.1f, %.1f)", nullptr },
			{ "Computed Size: (%.1f, %.1f)", "計算後のサイズ: (%.1f, %.1f)", nullptr },
			{ "Create", "作成", nullptr },
			{ "Create Child Entity", "子エンティティを作成", nullptr },
			{ "Create Empty Entity", "空のエンティティを作成", nullptr },
			{ "Create Entity", "エンティティを作成", nullptr },
			{ "Cursor: (%.1f,%.1f,%.1f)", "カーソル: (%.1f,%.1f,%.1f)", nullptr },
			{ "Delete Entity", "エンティティを削除", nullptr },
			{ "Discard", "破棄", nullptr },
			{ "Emissive Color", "発光カラー", nullptr },
			{ "Emissive Map", "発光マップ", nullptr },
			{ "Emissive Strength", "発光強度", nullptr },
			{ "Enabled", "有効", nullptr },
			{ "Entities: %u", "エンティティ数: %u", nullptr },
			{ "Exit", "終了", nullptr },
			{ "Exposure", "露出", nullptr },
			{ "FOV", "視野角(FOV)", nullptr },
			{ "Far Clip", "ファークリップ", nullptr },
			{ "File", "ファイル", nullptr },
			{ "Frequency", "周波数", nullptr },
			{ "Friction", "摩擦", nullptr },
			{ "Gradient (used when no texture)", "グラデーション(テクスチャ未設定時に使用)", nullptr },
			{ "Height", "高さ", nullptr },
			{ "Height Scale", "高さスケール", nullptr },
			{ "Horizon", "地平線", nullptr },
			{ "Hovered Color", "ホバー時の色", nullptr },
			{ "Hovered: %s", "ホバー: %s", nullptr },
			{ "Image Component", "画像コンポーネント", nullptr },
			{ "Initialized: %s", "初期化済み: %s", nullptr },
			{ "Inner Angle", "内角", nullptr },
			{ "Intensity", "強度", nullptr },
			{ "Interactable", "操作可能", nullptr },
			{ "Lacunarity", "ラクナリティ", nullptr },
			{ "Language", "言語", nullptr },
			{ "Light Component", "ライトコンポーネント", nullptr },
			{ "Loop", "ループ", nullptr },
			{ "Mass", "質量", nullptr },
			{ "Material (PBR)", "マテリアル (PBR)", nullptr },
			{ "Material Path", "マテリアルパス", nullptr },
			{ "Mesh Component", "メッシュコンポーネント", nullptr },
			{ "Mesh Path", "メッシュパス", nullptr },
			{ "Metallic", "メタリック", nullptr },
			{ "Metallic/Roughness Map (R=Metal,G=Rough)", "メタリック/ラフネスマップ (R=メタル, G=ラフ)", nullptr },
			{ "Move: %s", "移動: %s", nullptr },
			{ "Near Clip", "ニアクリップ", nullptr },
			{ "New", "新規", nullptr },
			{ "No active scene", "アクティブなシーンがありません", nullptr },
			{ "No primary camera in scene", "シーンにプライマリカメラがありません", nullptr },
			{ "Noise", "ノイズ", nullptr },
			{ "Normal Color", "通常時の色", nullptr },
			{ "Normal Map", "法線マップ", nullptr },
			{ "Octaves", "オクターブ", nullptr },
			{ "Outer Angle", "外角", nullptr },
			{ "PCF Radius", "PCF半径", nullptr },
			{ "Pause", "一時停止", nullptr },
			{ "Persistence", "パーシステンス", nullptr },
			{ "Physics", "物理", nullptr },
			{ "Pivot", "ピボット", nullptr },
			{ "Pixel Shader (optional)", "ピクセルシェーダー(任意)", nullptr },
			{ "Play", "再生", nullptr },
			{ "Play (Preview)", "再生(プレビュー)", nullptr },
			{ "Play On Awake", "起動時に再生", nullptr },
			{ "Position", "位置", nullptr },
			{ "Pressed Color", "押下時の色", nullptr },
			{ "Pressed: %s", "押下: %s", nullptr },
			{ "Primary", "プライマリ", nullptr },
			{ "Radius", "半径", nullptr },
			{ "Range", "範囲", nullptr },
			{ "Rect Transform", "矩形トランスフォーム", nullptr },
			{ "Reference Resolution", "基準解像度", nullptr },
			{ "Regenerate", "再生成", nullptr },
			{ "Registered: %s", "登録済み: %s", nullptr },
			{ "Reload Scripts", "スクリプトを再読み込み", nullptr },
			{ "Render Mode", "レンダーモード", nullptr },
			{ "Rendering", "レンダリング", nullptr },
			{ "Replay", "リプレイ", nullptr },
			{ "Resolution X", "解像度 X", nullptr },
			{ "Resolution Z", "解像度 Z", nullptr },
			{ "Restitution", "反発係数", nullptr },
			{ "Resume", "再開", nullptr },
			{ "Rigidbody Component", "リジッドボディコンポーネント", nullptr },
			{ "Rotation", "回転", nullptr },
			{ "Roughness", "ラフネス", nullptr },
			{ "Save", "保存", nullptr },
			{ "Save & Continue", "保存して続行", nullptr },
			{ "Save Material", "マテリアルを保存", nullptr },
			{ "Save Scene", "シーンを保存", nullptr },
			{ "Scale", "スケール", nullptr },
			{ "Scene", "シーン", nullptr },
			{ "Scene Name", "シーン名", nullptr },
			{ "Scene: %s", "シーン: %s", nullptr },
			{ "Script", "スクリプト", nullptr },
			{ "Script(C++) Component", "スクリプト(C++)コンポーネント", nullptr },
			{ "Script(lua) Component", "スクリプト(Lua)コンポーネント", nullptr },
			{ "Script: %s", "スクリプト: %s", nullptr },
			{ "Scripting", "スクリプティング", nullptr },
			{ "Sculpt (SceneView)", "スカルプト (SceneView)", nullptr },
			{ "Sculpt Mode", "スカルプトモード", nullptr },
			{ "Search files", "ファイルを検索", nullptr },
			{ "Seed", "シード", nullptr },
			{ "Settings", "設定", nullptr },
			{ "Shadow", "シャドウ", nullptr },
			{ "Shape", "形状", nullptr },
			{ "Size Delta", "サイズ差分", nullptr },
			{ "Size X", "サイズ X", nullptr },
			{ "Size Z", "サイズ Z", nullptr },
			{ "SkySphere Component", "スカイスフィアコンポーネント", nullptr },
			{ "Soft Shadow", "ソフトシャドウ", nullptr },
			{ "Sort Order", "描画順", nullptr },
			{ "Stop", "停止", nullptr },
			{ "Switch Scene", "シーン切り替え", nullptr },
			{ "Terrain", "地形", nullptr },
			{ "Terrain Field Component", "地形フィールドコンポーネント", nullptr },
			{ "Texture", "テクスチャ", nullptr },
			{ "Texture Path", "テクスチャパス", nullptr },
			{ "Top", "上", nullptr },
			{ "Transform", "トランスフォーム", nullptr },
			{ "Type", "タイプ", nullptr },
			{ "Unparent", "親子関係を解除", nullptr },
			{ "Unsaved Changes", "未保存の変更", nullptr },
			{ "Use Gravity", "重力を使用", nullptr },
			{ "Vertex Shader (optional)", "頂点シェーダー(任意)", nullptr },
			{ "Vertices: %u x %u", "頂点数: %u x %u", nullptr },
			{ "Vertices: %zu Indices: %zu SubMeshes: %zu", "頂点: %zu インデックス: %zu サブメッシュ: %zu", nullptr },
			{ "Visible", "表示", nullptr },
			{ "Volume", "音量", nullptr },
			{ "You have unsaved changes. Continue without saving?", "未保存の変更があります。保存せずに続行しますか?", nullptr },
			{ "[Refresh]", "[更新]", nullptr },
			{ "half Extents", "ハーフエクステント", nullptr },
			{ "no entity selected", "エンティティが選択されていません", nullptr },

			// ---- キーが日本語のもの (英語表示時の訳) ----
			{ "Pause中のみ質問できます(現在のフレーム範囲を固定するため)。", nullptr, "Questions can only be asked while paused (to fix the current frame range)." },
			{ "SceneView上でLMBドラッグで編集 / Shiftで反転(Raise/Lowerのみ)", nullptr, "Drag with LMB in SceneView to edit / Hold Shift to invert (Raise/Lower only)" },
			{ "editor_settings.json に平文で保存されます。リポジトリにコミットしないこと。", nullptr, "Stored in plain text in editor_settings.json. Do not commit it to the repository." },
			{ "リプレイの記録がありません。Play/Pauseしてフレームを記録してください。", nullptr, "No replay recorded. Press Play/Pause to record frames." },
			{ "対象フレーム: %11u", nullptr, "Target frame: %11u" },
			{ "送信", nullptr, "Send" },
			// ---- アニメーションイベント ----
			{ "Animation Events", "アニメーションイベント", nullptr },
			{ "Select an entity that has Animator and Mesh components", "AnimatorとMeshを持つエンティティを選択してください", nullptr },
			{ "This mesh has no animation clips", "このメッシュにはアニメーションクリップがありません", nullptr },
			{ "Clip", "クリップ", nullptr },
			{ "Select a clip", "クリップを選択してください", nullptr },
			{ "Speed", "速度", nullptr },
			{ "Zoom", "ズーム", nullptr },
			{ "Add at playhead:", "再生ヘッド位置に追加:", nullptr },
			{ "Add point event", "ポイントイベントを追加", nullptr },
			{ "Start (f)", "開始(f)", nullptr },
			{ "End (f)", "終了(f)", nullptr },
			{ "Tag", "タグ", nullptr },
			{ "Param", "パラメータ", nullptr },
			{ "Delete window", "窓を削除", nullptr },
			{ "Name", "名前", nullptr },
			{ "Payload", "ペイロード", nullptr },
			{ "Frame", "フレーム", nullptr },
			{ "Delete point", "ポイントを削除", nullptr },
			{ "Click a window or point to edit it", "窓またはポイントをクリックして編集", nullptr },
			{ "Live state:", "現在の状態:", nullptr },
			{ "If hit now", "今被弾した場合", nullptr },
			{ "Save *", "保存 *", nullptr },
			{ "Revert", "元に戻す", nullptr },
		};
	}

	void initLocalization()
	{
		FaluEngine::Loc::addEntries(kEntries, std::size(kEntries));

		const bool english = EditorSettings::get().getLanguage() == "en";
		FaluEngine::Loc::setLanguage(english ?
			FaluEngine::Loc::Language::English : FaluEngine::Loc::Language::Japanese);
	}

	void setLanguage(FaluEngine::Loc::Language lang)
	{
		FaluEngine::Loc::setLanguage(lang);

		auto& settings = EditorSettings::get();
		settings.setLanguage(lang == FaluEngine::Loc::Language::English ? "en" : "ja");
		settings.save();
	}
}
